[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run build"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
